//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.SOperador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsOperadoresSimple", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsOperadoresSimple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JerarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jerarquia {
            get {
                return this.JerarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.JerarquiaField, value) != true)) {
                    this.JerarquiaField = value;
                    this.RaisePropertyChanged("Jerarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsSuplentes", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsSuplentes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CarteraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DistribucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IndicadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReportesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupervisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSuplenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cartera {
            get {
                return this.CarteraField;
            }
            set {
                if ((this.CarteraField.Equals(value) != true)) {
                    this.CarteraField = value;
                    this.RaisePropertyChanged("Cartera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((this.CorreoField.Equals(value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Distribucion {
            get {
                return this.DistribucionField;
            }
            set {
                if ((this.DistribucionField.Equals(value) != true)) {
                    this.DistribucionField = value;
                    this.RaisePropertyChanged("Distribucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gestion {
            get {
                return this.GestionField;
            }
            set {
                if ((this.GestionField.Equals(value) != true)) {
                    this.GestionField = value;
                    this.RaisePropertyChanged("Gestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Indicadores {
            get {
                return this.IndicadoresField;
            }
            set {
                if ((this.IndicadoresField.Equals(value) != true)) {
                    this.IndicadoresField = value;
                    this.RaisePropertyChanged("Indicadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Reportes {
            get {
                return this.ReportesField;
            }
            set {
                if ((this.ReportesField.Equals(value) != true)) {
                    this.ReportesField = value;
                    this.RaisePropertyChanged("Reportes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Supervision {
            get {
                return this.SupervisionField;
            }
            set {
                if ((this.SupervisionField.Equals(value) != true)) {
                    this.SupervisionField = value;
                    this.RaisePropertyChanged("Supervision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSuplente {
            get {
                return this.idSuplenteField;
            }
            set {
                if ((this.idSuplenteField.Equals(value) != true)) {
                    this.idSuplenteField = value;
                    this.RaisePropertyChanged("idSuplente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsOperadores", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsOperadores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEgresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idGrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSupervisorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEgreso {
            get {
                return this.FechaEgresoField;
            }
            set {
                if ((this.FechaEgresoField.Equals(value) != true)) {
                    this.FechaEgresoField = value;
                    this.RaisePropertyChanged("FechaEgreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmaCorreo {
            get {
                return this.FirmaCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaCorreoField, value) != true)) {
                    this.FirmaCorreoField = value;
                    this.RaisePropertyChanged("FirmaCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Supervisor {
            get {
                return this.SupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorField, value) != true)) {
                    this.SupervisorField = value;
                    this.RaisePropertyChanged("Supervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefonos {
            get {
                return this.TelefonosField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonosField, value) != true)) {
                    this.TelefonosField = value;
                    this.RaisePropertyChanged("Telefonos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                if ((this.idGrupoField.Equals(value) != true)) {
                    this.idGrupoField = value;
                    this.RaisePropertyChanged("idGrupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSupervisor {
            get {
                return this.idSupervisorField;
            }
            set {
                if ((this.idSupervisorField.Equals(value) != true)) {
                    this.idSupervisorField = value;
                    this.RaisePropertyChanged("idSupervisor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsMetasOperador", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsMetasOperador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacturasCobradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MetaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PorcMetaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Facturas {
            get {
                return this.FacturasField;
            }
            set {
                if ((this.FacturasField.Equals(value) != true)) {
                    this.FacturasField = value;
                    this.RaisePropertyChanged("Facturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacturasCobradas {
            get {
                return this.FacturasCobradasField;
            }
            set {
                if ((this.FacturasCobradasField.Equals(value) != true)) {
                    this.FacturasCobradasField = value;
                    this.RaisePropertyChanged("FacturasCobradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Meta {
            get {
                return this.MetaField;
            }
            set {
                if ((this.MetaField.Equals(value) != true)) {
                    this.MetaField = value;
                    this.RaisePropertyChanged("Meta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MetaFija {
            get {
                return this.MetaFijaField;
            }
            set {
                if ((this.MetaFijaField.Equals(value) != true)) {
                    this.MetaFijaField = value;
                    this.RaisePropertyChanged("MetaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Porc {
            get {
                return this.PorcField;
            }
            set {
                if ((this.PorcField.Equals(value) != true)) {
                    this.PorcField = value;
                    this.RaisePropertyChanged("Porc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PorcMetaFija {
            get {
                return this.PorcMetaFijaField;
            }
            set {
                if ((this.PorcMetaFijaField.Equals(value) != true)) {
                    this.PorcMetaFijaField = value;
                    this.RaisePropertyChanged("PorcMetaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Real {
            get {
                return this.RealField;
            }
            set {
                if ((this.RealField.Equals(value) != true)) {
                    this.RealField = value;
                    this.RaisePropertyChanged("Real");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMeta {
            get {
                return this.idMetaField;
            }
            set {
                if ((this.idMetaField.Equals(value) != true)) {
                    this.idMetaField = value;
                    this.RaisePropertyChanged("idMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsOperadoresAsignaciones", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsOperadoresAsignaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idPais {
            get {
                return this.idPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idPaisField, value) != true)) {
                    this.idPaisField = value;
                    this.RaisePropertyChanged("idPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoCliente {
            get {
                return this.idTipoClienteField;
            }
            set {
                if ((this.idTipoClienteField.Equals(value) != true)) {
                    this.idTipoClienteField = value;
                    this.RaisePropertyChanged("idTipoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rptLoginsResult", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas")]
    [System.SerializableAttribute()]
    public partial class rptLoginsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fin {
            get {
                return this.FinField;
            }
            set {
                if ((this.FinField.Equals(value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCompromisosRpt", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsCompromisosRpt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoDolarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RestanteDolarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RestanteLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoDolar {
            get {
                return this.MontoDolarField;
            }
            set {
                if ((this.MontoDolarField.Equals(value) != true)) {
                    this.MontoDolarField = value;
                    this.RaisePropertyChanged("MontoDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoLocal {
            get {
                return this.MontoLocalField;
            }
            set {
                if ((this.MontoLocalField.Equals(value) != true)) {
                    this.MontoLocalField = value;
                    this.RaisePropertyChanged("MontoLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RestanteDolar {
            get {
                return this.RestanteDolarField;
            }
            set {
                if ((this.RestanteDolarField.Equals(value) != true)) {
                    this.RestanteDolarField = value;
                    this.RaisePropertyChanged("RestanteDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RestanteLocal {
            get {
                return this.RestanteLocalField;
            }
            set {
                if ((this.RestanteLocalField.Equals(value) != true)) {
                    this.RestanteLocalField = value;
                    this.RaisePropertyChanged("RestanteLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                if ((this.idPersonaField.Equals(value) != true)) {
                    this.idPersonaField = value;
                    this.RaisePropertyChanged("idPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsOperadoresSupervisor", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsOperadoresSupervisor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MontoMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MontoRecaudadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> porcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MontoMeta {
            get {
                return this.MontoMetaField;
            }
            set {
                if ((this.MontoMetaField.Equals(value) != true)) {
                    this.MontoMetaField = value;
                    this.RaisePropertyChanged("MontoMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MontoRecaudado {
            get {
                return this.MontoRecaudadoField;
            }
            set {
                if ((this.MontoRecaudadoField.Equals(value) != true)) {
                    this.MontoRecaudadoField = value;
                    this.RaisePropertyChanged("MontoRecaudado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> porc {
            get {
                return this.porcField;
            }
            set {
                if ((this.porcField.Equals(value) != true)) {
                    this.porcField = value;
                    this.RaisePropertyChanged("porc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOperador.IServicioOperador")]
    public interface IServicioOperador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_lst", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_lstResponse")]
        Cobranzas.SOperador.clsOperadoresSimple[] Operadores_lst();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_Suplantar_lst", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_Suplantar_lstResponse")]
        Cobranzas.SOperador.clsSuplentes[] Operadores_Suplantar_lst(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_Suplantarme_lst", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_Suplantarme_lstResponse")]
        Cobranzas.SOperador.clsSuplentes[] Operadores_Suplantarme_lst(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_sel", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_selResponse")]
        Cobranzas.SOperador.clsOperadores Operadores_sel(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_del", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_delResponse")]
        bool Operadores_del(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_sav", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_savResponse")]
        bool Operadores_sav(Cobranzas.SOperador.clsOperadores Operador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operador_Metas", ReplyAction="http://tempuri.org/IServicioOperador/Operador_MetasResponse")]
        Cobranzas.SOperador.clsMetasOperador[] Operador_Metas(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/DistribucionOperadores_Ejecutar", ReplyAction="http://tempuri.org/IServicioOperador/DistribucionOperadores_EjecutarResponse")]
        bool DistribucionOperadores_Ejecutar(int idDistribucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_Asignaciones_lst", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_Asignaciones_lstResponse")]
        Cobranzas.SOperador.clsOperadoresAsignaciones[] Operadores_Asignaciones_lst(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Operadores_Persona_lst", ReplyAction="http://tempuri.org/IServicioOperador/Operadores_Persona_lstResponse")]
        Cobranzas.SOperador.clsOperadoresSimple[] Operadores_Persona_lst(int idPersona, int[] Operadores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Nombre", ReplyAction="http://tempuri.org/IServicioOperador/NombreResponse")]
        string Nombre(int idOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Logins_rpt", ReplyAction="http://tempuri.org/IServicioOperador/Logins_rptResponse")]
        Cobranzas.SOperador.rptLoginsResult[] Logins_rpt(System.DateTime FechaDesde, System.DateTime FechaHasta, int idOperador, bool Supervisados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Salir", ReplyAction="http://tempuri.org/IServicioOperador/SalirResponse")]
        bool Salir(int idOperador, bool Impersonando);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/Compromisos_rpt", ReplyAction="http://tempuri.org/IServicioOperador/Compromisos_rptResponse")]
        Cobranzas.SOperador.clsCompromisosRpt[] Compromisos_rpt(int idOperador, System.DateTime FechaDesde, System.DateTime FechaHasta, bool Supervisado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioOperador/ListarOperadoresSUpervisor", ReplyAction="http://tempuri.org/IServicioOperador/ListarOperadoresSUpervisorResponse")]
        Cobranzas.SOperador.clsOperadoresSupervisor[] ListarOperadoresSUpervisor(int idOperador, System.DateTime fecha1, System.DateTime fecha2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioOperadorChannel : Cobranzas.SOperador.IServicioOperador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioOperadorClient : System.ServiceModel.ClientBase<Cobranzas.SOperador.IServicioOperador>, Cobranzas.SOperador.IServicioOperador {
        
        public ServicioOperadorClient() {
        }
        
        public ServicioOperadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioOperadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioOperadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioOperadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cobranzas.SOperador.clsOperadoresSimple[] Operadores_lst() {
            return base.Channel.Operadores_lst();
        }
        
        public Cobranzas.SOperador.clsSuplentes[] Operadores_Suplantar_lst(int idOperador) {
            return base.Channel.Operadores_Suplantar_lst(idOperador);
        }
        
        public Cobranzas.SOperador.clsSuplentes[] Operadores_Suplantarme_lst(int idOperador) {
            return base.Channel.Operadores_Suplantarme_lst(idOperador);
        }
        
        public Cobranzas.SOperador.clsOperadores Operadores_sel(int idOperador) {
            return base.Channel.Operadores_sel(idOperador);
        }
        
        public bool Operadores_del(int idOperador) {
            return base.Channel.Operadores_del(idOperador);
        }
        
        public bool Operadores_sav(Cobranzas.SOperador.clsOperadores Operador) {
            return base.Channel.Operadores_sav(Operador);
        }
        
        public Cobranzas.SOperador.clsMetasOperador[] Operador_Metas(int idOperador) {
            return base.Channel.Operador_Metas(idOperador);
        }
        
        public bool DistribucionOperadores_Ejecutar(int idDistribucion) {
            return base.Channel.DistribucionOperadores_Ejecutar(idDistribucion);
        }
        
        public Cobranzas.SOperador.clsOperadoresAsignaciones[] Operadores_Asignaciones_lst(int idOperador) {
            return base.Channel.Operadores_Asignaciones_lst(idOperador);
        }
        
        public Cobranzas.SOperador.clsOperadoresSimple[] Operadores_Persona_lst(int idPersona, int[] Operadores) {
            return base.Channel.Operadores_Persona_lst(idPersona, Operadores);
        }
        
        public string Nombre(int idOperador) {
            return base.Channel.Nombre(idOperador);
        }
        
        public Cobranzas.SOperador.rptLoginsResult[] Logins_rpt(System.DateTime FechaDesde, System.DateTime FechaHasta, int idOperador, bool Supervisados) {
            return base.Channel.Logins_rpt(FechaDesde, FechaHasta, idOperador, Supervisados);
        }
        
        public bool Salir(int idOperador, bool Impersonando) {
            return base.Channel.Salir(idOperador, Impersonando);
        }
        
        public Cobranzas.SOperador.clsCompromisosRpt[] Compromisos_rpt(int idOperador, System.DateTime FechaDesde, System.DateTime FechaHasta, bool Supervisado) {
            return base.Channel.Compromisos_rpt(idOperador, FechaDesde, FechaHasta, Supervisado);
        }
        
        public Cobranzas.SOperador.clsOperadoresSupervisor[] ListarOperadoresSUpervisor(int idOperador, System.DateTime fecha1, System.DateTime fecha2) {
            return base.Channel.ListarOperadoresSUpervisor(idOperador, fecha1, fecha2);
        }
    }
}
