//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.ranking {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsMetasOperador", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCobranzas.Entidades")]
    [System.SerializableAttribute()]
    public partial class clsMetasOperador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacturasCobradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MetaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PorcMetaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOperadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Facturas {
            get {
                return this.FacturasField;
            }
            set {
                if ((this.FacturasField.Equals(value) != true)) {
                    this.FacturasField = value;
                    this.RaisePropertyChanged("Facturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacturasCobradas {
            get {
                return this.FacturasCobradasField;
            }
            set {
                if ((this.FacturasCobradasField.Equals(value) != true)) {
                    this.FacturasCobradasField = value;
                    this.RaisePropertyChanged("FacturasCobradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Meta {
            get {
                return this.MetaField;
            }
            set {
                if ((this.MetaField.Equals(value) != true)) {
                    this.MetaField = value;
                    this.RaisePropertyChanged("Meta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MetaFija {
            get {
                return this.MetaFijaField;
            }
            set {
                if ((this.MetaFijaField.Equals(value) != true)) {
                    this.MetaFijaField = value;
                    this.RaisePropertyChanged("MetaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Porc {
            get {
                return this.PorcField;
            }
            set {
                if ((this.PorcField.Equals(value) != true)) {
                    this.PorcField = value;
                    this.RaisePropertyChanged("Porc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PorcMetaFija {
            get {
                return this.PorcMetaFijaField;
            }
            set {
                if ((this.PorcMetaFijaField.Equals(value) != true)) {
                    this.PorcMetaFijaField = value;
                    this.RaisePropertyChanged("PorcMetaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Real {
            get {
                return this.RealField;
            }
            set {
                if ((this.RealField.Equals(value) != true)) {
                    this.RealField = value;
                    this.RaisePropertyChanged("Real");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMeta {
            get {
                return this.idMetaField;
            }
            set {
                if ((this.idMetaField.Equals(value) != true)) {
                    this.idMetaField = value;
                    this.RaisePropertyChanged("idMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOperador {
            get {
                return this.idOperadorField;
            }
            set {
                if ((this.idOperadorField.Equals(value) != true)) {
                    this.idOperadorField = value;
                    this.RaisePropertyChanged("idOperador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ranking.IServicioRanking")]
    public interface IServicioRanking {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRanking/Ranking_lst", ReplyAction="http://tempuri.org/IServicioRanking/Ranking_lstResponse")]
        Cobranzas.ranking.clsMetasOperador[] Ranking_lst(int idMeta, System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRanking/Ranking_Operador_lst", ReplyAction="http://tempuri.org/IServicioRanking/Ranking_Operador_lstResponse")]
        Cobranzas.ranking.clsMetasOperador[] Ranking_Operador_lst(int idOperador, System.DateTime Fecha1, System.DateTime Fecha2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRankingChannel : Cobranzas.ranking.IServicioRanking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRankingClient : System.ServiceModel.ClientBase<Cobranzas.ranking.IServicioRanking>, Cobranzas.ranking.IServicioRanking {
        
        public ServicioRankingClient() {
        }
        
        public ServicioRankingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRankingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRankingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRankingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cobranzas.ranking.clsMetasOperador[] Ranking_lst(int idMeta, System.DateTime Fecha) {
            return base.Channel.Ranking_lst(idMeta, Fecha);
        }
        
        public Cobranzas.ranking.clsMetasOperador[] Ranking_Operador_lst(int idOperador, System.DateTime Fecha1, System.DateTime Fecha2) {
            return base.Channel.Ranking_Operador_lst(idOperador, Fecha1, Fecha2);
        }
    }
}
